Port to Rails, add images
saasbook/esaasbook pull request #6
Opened 2022-04-10 23:25 UTC by JDDelrosario

This PR is the port to Rails and addition of images to the textbook. The underlying structure for user authentication is also included, however there is currently no user-facing way to log-in.

Due to the nature of this PR, a massive number of file changes are listed. Unfortunately due to the underlying structure of what we were provided (hundreds upon hundreds of HTML and image files) there is no clean way around this for the initial PR.

The staging version of the site can be viewed here: https://esaas169l.herokuapp.com/

Please remember to run a DB migrate after merging.

The following environment variables must be added to heroku (or whatever deployment solution the main site is using):
GITHUB_APP_ID
GITHUB_APP_SECRET

2022-04-12 04:35 UTC, pamelafox commented on app/controllers/saasbook_controller.rb
> +# Controller for the Saasbook website. Temporary maybe?
This comment ("Temporary maybe?") seems likely to become obsolete or to confuse future developers.
Suggest adding more information for future developers, like
# NOTE(4/11/22): This is likely to be replaced in the future by....

2022-04-12 04:56 UTC, pamelafox commented
High level comments:
* I was surprised to see a pycache folder checked in, I wouldn't normally think pyc files would be checked in.
* I noticed two fonts directories that seemed either the same or similar, are they both in use?
* Are all the CSS files being used under stylesheets? Clicking around, it seemed like many of them are themes. Is there one theme you use?
* What do the .keep files do? (Do they actually do something?)
* Does old_site need to be checked in? (Can it not be retrieved from git history?)

2022-04-12 04:56 UTC, pamelafox commented on app/controllers/users/omniauth_controller.rb
> +      # Can change redirect/message later
This comment may also be perplexing to future developers, who might wonder if they should be changing the later.

2022-04-12 04:56 UTC, pamelafox commented on app/jobs/application_job.rb
> +class ApplicationJob < ActiveJob::Base
These three files all seem auto-generated? Is it typical to keep the default files checked in, even if you're not using them? I dont believe you have jobs or mailing functionality in your app, right?

2022-04-12 04:56 UTC, pamelafox commented on app/views/layouts/application.html.erb
> +    <title>Esaasbook</title>
This doesn't seem to match the title on http://e.saasbook.info/

2022-04-12 04:56 UTC, pamelafox commented on app/views/saasbook/_chapter1.html.erb
> +<main class="col py-md-3 pl-md-4 bd-content overflow-auto" role="main">
Quite a lot of this code seems repeated across these chapter files. Can it not be partials? Or extensions of a base template?

2022-04-12 04:56 UTC, pamelafox commented on app/views/saasbook/book_content.html.erb
> +        <title>1. Introduction to Software as a Service, Agile Development, and Cloud Computing &#8212; saasbook  documentation</title>
Is this title correct for all the places this ERB is used? (This title is Chapter 1's title)

2022-04-12 04:56 UTC, pamelafox commented on features/support/env.rb
> +# frozen_string_literal: true
This comment was already at the top?

2022-04-12 04:56 UTC, pamelafox commented on info.yml
> +      githubUsername: ' '
Intentionally left blank?

2022-04-19 18:23 UTC, sme777 requested changes

2022-04-19 18:23 UTC, sme777 commented on app/assets/javascript/book_content.js
> +    let my_loc = window.location.href;
Change variable names to camelCase.

2022-04-19 18:23 UTC, sme777 commented on app/jobs/application_job.rb
> +class ApplicationJob < ActiveJob::Base
Agree, I don't think there's a need to have these files.

2022-04-19 18:23 UTC, sme777 commented on app/views/saasbook/_chapter10section3.html.erb
> +            &copy; Copyright 2021, Armando Fox and David Patterson.<br/>
Change Copyright to 2022.

2022-04-21 05:41 UTC, pamelafox commented on .github/workflows/main.yml
> +        $CCTR upload-coverage -r 7a9538a8a8f2fa88c9fe5416165132f9c62b066b37459128886f322a3fed501d
Hm, so the bay birding repo stores their CC id as a repository secret. I also see that in examples online. I'm not positive how secretive the ID needs to be, but it's also the case that this ID is likely for one of your personal accounts, and the golden repo should likely be tied to a different account, so can you change this to a secret?
Here's the bird repo CI yaml:
https://github.com/saasbook/baytrailbirding/blob/main/.github/workflows/ci.yml
Let me know if you have reason to believe it shouldn't be a secret.

2022-04-21 05:42 UTC, pamelafox commented on README.md
> +[![Maintainability](https://api.codeclimate.com/v1/badges/659a72a1faefbcbf7565/maintainability)](https://codeclimate.com/github/ChuanHuoGe/esaasbook/maintainability)
Note: For a future PR, you're going to want to add installation/deployment instructions to the README, so that a project hand-off can be smooth!

2022-04-21 05:50 UTC, pamelafox commented
The Armando image is 2334*3506, 4.5MB, which is way too large for how it's used, can you resize it to a more appropriate size to save user bandwidth?

Let us know when you're ready for a re-review!

2022-04-26 06:21 UTC, JDDelrosario commented on app/controllers/saasbook_controller.rb
> +# Controller for the Saasbook website. Temporary maybe?
Addressed by https://github.com/ChuanHuoGe/esaasbook/pull/43

2022-04-26 06:21 UTC, JDDelrosario commented on app/controllers/users/omniauth_controller.rb
> +      # Can change redirect/message later
Addressed by https://github.com/ChuanHuoGe/esaasbook/pull/43

2022-04-26 06:21 UTC, JDDelrosario commented on app/jobs/application_job.rb
> +class ApplicationJob < ActiveJob::Base
Addressed by https://github.com/ChuanHuoGe/esaasbook/pull/45

2022-04-26 06:22 UTC, JDDelrosario commented on app/views/saasbook/_chapter1.html.erb
> +<main class="col py-md-3 pl-md-4 bd-content overflow-auto" role="main">
Addressed by https://github.com/ChuanHuoGe/esaasbook/pull/37

(Somehow two tasks got condensed into this PR, but condensing common code into partials is under this PR)

2022-04-26 06:22 UTC, JDDelrosario commented on app/views/layouts/application.html.erb
> +    <title>Esaasbook</title>
Addressed by https://github.com/ChuanHuoGe/esaasbook/pull/40

2022-04-26 06:22 UTC, JDDelrosario commented on app/views/saasbook/book_content.html.erb
> +        <title>1. Introduction to Software as a Service, Agile Development, and Cloud Computing &#8212; saasbook  documentation</title>
Addressed by https://github.com/ChuanHuoGe/esaasbook/pull/40

2022-04-26 06:23 UTC, JDDelrosario commented on features/support/env.rb
> +# frozen_string_literal: true
Addressed by https://github.com/ChuanHuoGe/esaasbook/pull/43

2022-04-26 06:23 UTC, JDDelrosario commented on info.yml
> +      githubUsername: ' '
Addressed by https://github.com/ChuanHuoGe/esaasbook/pull/43

2022-04-26 06:23 UTC, JDDelrosario commented on app/assets/javascript/book_content.js
> +    let my_loc = window.location.href;
Addressed by https://github.com/ChuanHuoGe/esaasbook/pull/41

2022-04-26 06:24 UTC, JDDelrosario commented on app/views/saasbook/_chapter10section3.html.erb
> +            &copy; Copyright 2021, Armando Fox and David Patterson.<br/>
Addressed by https://github.com/ChuanHuoGe/esaasbook/pull/37

2022-04-26 06:24 UTC, JDDelrosario commented on .github/workflows/main.yml
> +        $CCTR upload-coverage -r 7a9538a8a8f2fa88c9fe5416165132f9c62b066b37459128886f322a3fed501d
Addressed by https://github.com/ChuanHuoGe/esaasbook/pull/47

2022-04-26 06:24 UTC, JDDelrosario commented on README.md
> +[![Maintainability](https://api.codeclimate.com/v1/badges/659a72a1faefbcbf7565/maintainability)](https://codeclimate.com/github/ChuanHuoGe/esaasbook/maintainability)
Addressed by https://github.com/ChuanHuoGe/esaasbook/pull/42

2022-04-26 06:27 UTC, JDDelrosario commented
All comments have been addressed.

Additional functionality has been added to the site:
-[Users can now make highlights and annotations when logged in.](https://github.com/ChuanHuoGe/esaasbook/pull/39)
-[Users can now view their profiles by clicking their avatar/username at the top right of the screen.](https://github.com/ChuanHuoGe/esaasbook/pull/37) User profiles contain a list of all the pages that a user has made annotations on, and additionally have a button for logging out.

The ReadMe has been updated with deployment instructions as well as a "to-do" list of stuff we would have liked to accomplish but did not have time to do.

2022-04-28 21:49 UTC, pamelafox requested changes
I believe these comments are all ones we discussed in the sync.

2022-04-28 21:49 UTC, pamelafox commented on app/assets/javascript/highlight-annotate.js
> +        underyling.style when we are downloading them from the server. Trying to do that
Typo underyling

2022-04-28 21:49 UTC, pamelafox commented on app/assets/javascript/highlight-annotate.js
> +    reco.on('selectAnnotation', function(a) {
Unneeded?

2022-04-28 21:49 UTC, pamelafox commented on app/assets/javascript/highlight-annotate.js
> +        $("#Blue").click(function() {changeHighlightColor(2);})
Consider something like:
  colors.forEach(function(color, index) {
     document.getElementById(color).addEventListener("click", function() {
        console.log(index);
      })
   })

2022-04-28 21:49 UTC, pamelafox commented on app/assets/javascript/highlight-annotate.js
> +        for (i=0; i<highlighterColors.length; i++) {
Put var in front of i, otherwise it becomes a global variable.
You can also use highlighterColors.forEach here. Ah, perhaps this can be merged with the code suggested below, I didn't realize they're both going through highlighterColors.

2022-04-28 21:49 UTC, pamelafox commented on app/assets/javascript/highlight-annotate.js
> +            $("#highlight-button").css("color","");
nit: space after comma

2022-04-28 21:49 UTC, pamelafox commented on app/assets/javascript/highlight-annotate.js
> +        let sectionId = $('.page_information').data('section');
You could DRY this into a func 
getPageInfo() { let ...let... return {chapter: ..., section: ....})
and use it both here and above.

2022-04-28 21:49 UTC, pamelafox commented on app/assets/javascript/highlight-annotate.js
> +            function(data, textStatus, jqXHR){loadAnnotations(data)}
if you're not using textStatus/jqXHR, I think its considered better to just leave them off, since data is the first param anyway

2022-04-28 21:49 UTC, pamelafox commented on app/assets/javascript/highlight-annotate.js
> +        The e.stopPropogation() flag is because after clicking the highlight button,
Helpful comment, I'd just situate it closer to the relevant line of code.
(It's also not a flag at least how I think of flags, it's a method call/function call).

2022-04-28 21:49 UTC, pamelafox commented on app/assets/javascript/highlight-annotate.js
> +    $("#highlight-button").click(function(e) { clickedHighlightButton(e) });
You should be able to simplify to:
$("#highlight-button").click(clickedHighlightButton)

2022-04-28 21:49 UTC, pamelafox commented on app/assets/stylesheets/custom.css
> +.dropdown-menu {
Make more specific by adding tag name, other class name, ID, or by prefixing it with its parent selectors.

2022-04-28 21:49 UTC, pamelafox commented on app/assets/stylesheets/custom.css
> +.dropdown-menu {
(Same for all selectors here that use !important)

2022-04-28 21:49 UTC, pamelafox commented on app/assets/stylesheets/image.css
> +/* figure {
Either delete or explain commented out code

2022-04-28 21:49 UTC, pamelafox commented on app/assets/stylesheets/image.css
> +  font-size:12px;
Space before property value

2022-04-28 21:49 UTC, pamelafox commented on app/assets/stylesheets/image.css
> +*/
This file uses 2 spaces, other CSS file uses 4 spaces. Pick one amount of spacing to be consistent.

2022-04-28 21:49 UTC, pamelafox commented on app/views/users/_user_page.html.erb
> +            <% next if eval(x.annotation).empty? %>
Do it without eval() - since users might do some Ruby injection otherwise
Check if its []

2022-04-28 21:49 UTC, pamelafox commented on app/views/users/_user_page.html.erb
> +            <% @annotations.each do |x| %>
High-level: I suggest moving the link generation logic to Ruby, so that you dont need to have datastore queries inside an ERB and so you can more easily test it.
Also, if possible, try to use only one database query for the whole page.

2022-04-29 00:09 UTC, sme777 requested changes

2022-04-29 00:09 UTC, sme777 commented on app/helpers/application_helper.rb
> +end
Do you need this class?

2022-04-29 00:09 UTC, sme777 commented on app/helpers/saasbook_helper.rb
> +# frozen_string_literal: true
Do you need these classes?

2022-04-29 00:09 UTC, sme777 commented on app/views/saasbook/_chapter1.html.erb
> +              </div>
Add proper indentation the unordered list and other tags.

2022-04-29 00:09 UTC, sme777 commented on app/views/saasbook/_chapter10.html.erb
> +              </div>
Add proper indentation the unordered list and other tags.

2022-04-29 00:09 UTC, sme777 commented on app/views/saasbook/_chapter10section1.html.erb
> +and quality means software de- velopment now is primarily a team sport. Hence,
Consider running an html linter.

2022-04-29 00:09 UTC, sme777 commented on app/views/saasbook/_chapter10section2.html.erb
> +branches can even be split off from other branches, but overly complex branching structures
Consider running an html linter.

2022-04-29 00:09 UTC, sme777 commented on app/views/saasbook/_chapter10section3.html.erb
> +and <em>then</em> try to apply your own commits. This latter step may cause conflicts if the 3 commits
Consider running an html linter.

2022-04-29 00:09 UTC, sme777 commented on app/views/saasbook/_chapter10section4.html.erb
> +workflow for Agile teams, in this section we describe a widely-used workflow and suggest
Consider running an html linter.

2022-04-29 00:09 UTC, sme777 commented on app/views/saasbook/_chapter10section6.html.erb
> +a regular user story. An advantage of this tool is that Tracker manages the bug’s lifecycle for
Consider running an html linter.

2022-04-29 00:09 UTC, sme777 commented on app/views/saasbook/_chapter10section8.html.erb
> +current changes; <em>after</em> you pull, merge or switch branches, reload any files in your editor
Consider running an html linter.

2022-04-29 00:09 UTC, sme777 commented on app/views/saasbook/_chapter10section9.html.erb
> +about 1970–1985, the original Unix <strong>Source Code Control System</strong> (SCCS) and its longer-lived
Consider running an html linter.

2022-04-29 00:09 UTC, sme777 commented on app/views/saasbook/_chapter12.html.erb
> +<li class="toctree-l1"><a class="reference internal" href="<%= section_path(chapter_id: 12, section_id: 6) %>">12.6. Improving Rendering and Database Performance With Caching</a></li>
If running on VS code, you can use Beautify extension to fix the indentations.

2022-04-29 18:36 UTC, JDDelrosario commented on app/views/saasbook/_chapter1.html.erb
> +              </div>
HTML files were auto generated and extracted from Sphinxbook. If site updates are planned to be done in the same way, we will not be hand-linting this HTML or manually fixing indentation as it will be automatically broken again when updating the site.

2022-04-29 18:36 UTC, JDDelrosario commented on app/views/saasbook/_chapter10.html.erb
> +              </div>
HTML files were auto generated and extracted from Sphinxbook. If site updates are planned to be done in the same way, we will not be hand-linting this HTML or manually fixing indentation as it will be automatically broken again when updating the site.

2022-04-29 18:36 UTC, JDDelrosario commented on app/views/saasbook/_chapter10section1.html.erb
> +and quality means software de- velopment now is primarily a team sport. Hence,
HTML files were auto generated and extracted from Sphinxbook. If site updates are planned to be done in the same way, we will not be hand-linting this HTML or manually fixing indentation as it will be automatically broken again when updating the site.

2022-04-29 18:36 UTC, JDDelrosario commented on app/views/saasbook/_chapter10section2.html.erb
> +branches can even be split off from other branches, but overly complex branching structures
HTML files were auto generated and extracted from Sphinxbook. If site updates are planned to be done in the same way, we will not be hand-linting this HTML or manually fixing indentation as it will be automatically broken again when updating the site.

2022-04-29 18:36 UTC, JDDelrosario commented on app/views/saasbook/_chapter10section3.html.erb
> +and <em>then</em> try to apply your own commits. This latter step may cause conflicts if the 3 commits
HTML files were auto generated and extracted from Sphinxbook. If site updates are planned to be done in the same way, we will not be hand-linting this HTML or manually fixing indentation as it will be automatically broken again when updating the site.

2022-04-29 18:36 UTC, JDDelrosario commented on app/views/saasbook/_chapter10section4.html.erb
> +workflow for Agile teams, in this section we describe a widely-used workflow and suggest
HTML files were auto generated and extracted from Sphinxbook. If site updates are planned to be done in the same way, we will not be hand-linting this HTML or manually fixing indentation as it will be automatically broken again when updating the site.

2022-04-29 18:37 UTC, JDDelrosario commented on app/views/saasbook/_chapter10section6.html.erb
> +a regular user story. An advantage of this tool is that Tracker manages the bug’s lifecycle for
HTML files were auto generated and extracted from Sphinxbook. If site updates are planned to be done in the same way, we will not be hand-linting this HTML or manually fixing indentation as it will be automatically broken again when updating the site.

2022-04-29 18:37 UTC, JDDelrosario commented on app/views/saasbook/_chapter10section8.html.erb
> +current changes; <em>after</em> you pull, merge or switch branches, reload any files in your editor
HTML files were auto generated and extracted from Sphinxbook. If site updates are planned to be done in the same way, we will not be hand-linting this HTML or manually fixing indentation as it will be automatically broken again when updating the site.

2022-04-29 18:37 UTC, JDDelrosario commented on app/views/saasbook/_chapter10section9.html.erb
> +about 1970–1985, the original Unix <strong>Source Code Control System</strong> (SCCS) and its longer-lived
HTML files were auto generated and extracted from Sphinxbook. If site updates are planned to be done in the same way, we will not be hand-linting this HTML or manually fixing indentation as it will be automatically broken again when updating the site.

2022-04-29 18:37 UTC, JDDelrosario commented on app/views/saasbook/_chapter12.html.erb
> +<li class="toctree-l1"><a class="reference internal" href="<%= section_path(chapter_id: 12, section_id: 6) %>">12.6. Improving Rendering and Database Performance With Caching</a></li>
HTML files were auto generated and extracted from Sphinxbook. If site updates are planned to be done in the same way, we will not be hand-linting this HTML or manually fixing indentation as it will be automatically broken again when updating the site.

2022-04-29 18:41 UTC, JDDelrosario commented
Re: HTML nitpicks: The HTML was all automatically generated by Sphinxbook via your RSTs. If this is the intended method of updating for the future then I would prefer to not hand-lint these HTML files.

If we had additional time for the project I would try to implement some auto-linter for HTML, however not enough time remains to do the proper setup and integration of such a tool. I'll add it to the readme as a task for future generations.

2022-05-02 08:19 UTC, JDDelrosario commented on app/assets/javascript/highlight-annotate.js
> +        underyling.style when we are downloading them from the server. Trying to do that
Addressed in https://github.com/ChuanHuoGe/esaasbook/pull/48

2022-05-02 08:20 UTC, JDDelrosario commented on app/assets/javascript/highlight-annotate.js
> +    reco.on('selectAnnotation', function(a) {
Addressed in https://github.com/ChuanHuoGe/esaasbook/pull/48

2022-05-02 08:20 UTC, JDDelrosario commented on app/assets/javascript/highlight-annotate.js
> +        $("#Blue").click(function() {changeHighlightColor(2);})
Addressed in https://github.com/ChuanHuoGe/esaasbook/pull/48

2022-05-02 08:20 UTC, JDDelrosario commented on app/assets/javascript/highlight-annotate.js
> +        for (i=0; i<highlighterColors.length; i++) {
Addressed in https://github.com/ChuanHuoGe/esaasbook/pull/48

2022-05-02 08:20 UTC, JDDelrosario commented on app/assets/javascript/highlight-annotate.js
> +            $("#highlight-button").css("color","");
Addressed in https://github.com/ChuanHuoGe/esaasbook/pull/48

2022-05-02 08:20 UTC, JDDelrosario commented on app/assets/javascript/highlight-annotate.js
> +        let sectionId = $('.page_information').data('section');
Addressed in https://github.com/ChuanHuoGe/esaasbook/pull/48

2022-05-02 08:20 UTC, JDDelrosario commented on app/assets/javascript/highlight-annotate.js
> +            function(data, textStatus, jqXHR){loadAnnotations(data)}
Addressed in https://github.com/ChuanHuoGe/esaasbook/pull/48

2022-05-02 08:20 UTC, JDDelrosario commented on app/assets/javascript/highlight-annotate.js
> +        The e.stopPropogation() flag is because after clicking the highlight button,
Addressed in https://github.com/ChuanHuoGe/esaasbook/pull/48

2022-05-02 08:20 UTC, JDDelrosario commented on app/assets/javascript/highlight-annotate.js
> +    $("#highlight-button").click(function(e) { clickedHighlightButton(e) });
Addressed in https://github.com/ChuanHuoGe/esaasbook/pull/48

2022-05-02 08:21 UTC, JDDelrosario commented on app/views/users/_user_page.html.erb
> +            <% next if eval(x.annotation).empty? %>
Addressed by https://github.com/ChuanHuoGe/esaasbook/pull/50

2022-05-02 08:21 UTC, JDDelrosario commented on app/views/users/_user_page.html.erb
> +            <% @annotations.each do |x| %>
Addressed by https://github.com/ChuanHuoGe/esaasbook/pull/50

2022-05-02 08:21 UTC, JDDelrosario commented on app/helpers/application_helper.rb
> +end
Addressed by https://github.com/ChuanHuoGe/esaasbook/pull/49

2022-05-02 08:21 UTC, JDDelrosario commented on app/helpers/saasbook_helper.rb
> +# frozen_string_literal: true
Addressed by https://github.com/ChuanHuoGe/esaasbook/pull/49

2022-05-02 08:58 UTC, JDDelrosario commented on app/assets/stylesheets/image.css
> +*/
Resolved by https://github.com/ChuanHuoGe/esaasbook/pull/51

2022-05-02 08:58 UTC, JDDelrosario commented on app/assets/stylesheets/image.css
> +  font-size:12px;
Resolved by https://github.com/ChuanHuoGe/esaasbook/pull/51

2022-05-02 08:58 UTC, JDDelrosario commented on app/assets/stylesheets/image.css
> +/* figure {
Resolved by https://github.com/ChuanHuoGe/esaasbook/pull/51

2022-05-02 08:59 UTC, JDDelrosario commented on app/assets/stylesheets/custom.css
> +.dropdown-menu {
Resolved by https://github.com/ChuanHuoGe/esaasbook/pull/51

The dropdown menu unfortunately cannot be overridden by specificity due to Bootstrap's javascript directly injecting a style attribute into the HTML. We are going to keep the !important tag for that one, because the alternative adds a lot of needless complexity.

2022-05-02 09:00 UTC, JDDelrosario commented
All comments have been addressed by the following PRs:
https://github.com/ChuanHuoGe/esaasbook/pull/48
https://github.com/ChuanHuoGe/esaasbook/pull/49
https://github.com/ChuanHuoGe/esaasbook/pull/50
https://github.com/ChuanHuoGe/esaasbook/pull/51

2022-05-02 15:46 UTC, pamelafox approved these changes
I reviewed the individual PRs, looks good, thanks for addressing feedback! @sme777 Over to you for final approval.

2022-05-02 18:14 UTC, sme777 approved these changes

2022-05-03 19:22 UTC, merged